### ISSUE TITLE
Senior Thesis Import to Production

### ISSUE THREAD

**Issue by bess** [pulibrary/etd_transformer#127]
Tracking spreadsheet here - https://docs.google.com/spreadsheets/d/1CCHpwIbz9Ehq2GEUAmcnwySdko6Ir6hMr5BmgrSaa9I/edit#gid=0

Google drive with relevant documents: https://drive.google.com/drive/u/1/folders/1wJyBK4HiVL6mbufycwV5vjUZyedI7ePO

- [x] African American Studies
- [x] Anthropology
- [x] Architecture School*
- [x] Art and Archaeology
- [x] Astrophysical Sciences
- [x] Chemical and Biological Engineering
- [x] Chemistry
- [x] Civil and Environmental Engineering
- [x] Classics
- [x] Comparative Literature
- [x] Computer Science
- [x] East Asian Studies
- [x] Ecology and Evolutionary Biology
- [x] Economics
- [x] Electrical Engineering
- [x] English
- [x] French and Italian
- [x] Geosciences
- [x] German
- [x] History
- [x] Independent Concentration (AB and LN)
- [x] Mathematics
- [x] Mechanical and Aerospace Engineering
- [x] Molecular Biology
- [x] Music
- [x] Near Eastern Studies
- [x] Neuroscience
- [x] Operations Research and Financial Engineering
- [x] Philosophy
- [x] Physics
- [x] Politics*
- [x] Psychology
- [x] Religion
- [x] Slavic Languages and Literature
- [x] Sociology
- [x] Spanish and Portuguese Languages and Cultures
- [x] School of Public and International Affairs*
- [x] Creative Writing Program
- [ ] Global Health and Health Policy Program

## Need collections created
- [ ] Robotics and Intelligent Systems Program
- [ ] South Asian Studies Program

**Comment by kelynch** [comment]
Three remaining theses will be put into a separate ticket.
