### ISSUE TITLE
Update format of embargo date for Alma

### ISSUE THREAD

**Issue by kelynch** [pulibrary/etd_transformer#159]
Update format of embargo date inserted into MARC XML for dissertations [here](https://github.com/pulibrary/etd_transformer/blob/main/dissertations_catalog/DISS2MARCXML.xsl) to be `YYYYMMDD`.

**Comment by bess** [comment]
I took a swing at this but couldn't figure it out. I took my name off of it, but it still displays my picture on zenhub. :(
