### ISSUE TITLE
Augment metadata with multiple authors

### ISSUE THREAD

**Issue by bess** [pulibrary/etd_transformer#4]
Some theses have multiple authors and this must be taken from the spreadsheet and applied to the thesis metadata.

**Comment by kmcelwee** [comment]
Senior theses that have multiple authors are often in the stem fields. Multiple students would then submit the same thesis. So we need to collapse the rows (and submissions) while enhancing the metadata with multiple authors. Look for the "Multi Author" boolean in the Vireo excel export. Here is an example spreadsheet from 2020's Mechanical Engineering program: 
[ExcelExport.xlsx](https://github.com/pulibrary/vireo_transformation/files/6274463/ExcelExport.xlsx)
